### PR TITLE
72 write spss2 produces a syntax which is not executable in spss

### PR DESCRIPTION
**Pull request by sachseka**
okay, now finally finished, please check

### CODE REVIEW

**Review by beckerbenj — CHANGES_REQUESTED** [review]
Thanks for the changes and bugfix!

I am a bit unsure about the scope of the changes. The bug was triggered by a variable that contained only `NAs`, for which the suggested changes make a lot of sense. However, could the format information also be missing due to a user forgetting about setting format for a variable? Or is this accounted for somewhere else in the function?

Some further minor comments:
- Could a news entry be added for this change?
- Would `anyUnknownFormat` be more fitting than `unknownFormat`?
- Currently, there is a lot of redundant subsetting in checkFormat (e.g., `GADSdat$dat[, hh]`, which can make the code slower than necessary and also hinders readability. Could in such instances intermediate objects help?

**Comment by sachseka** [comment]
> I am a bit unsure about the scope of the changes. The bug was triggered by a variable that contained only `NAs`, for which the suggested changes make a lot of sense. However, could the format information also be missing due to a user forgetting about setting format for a variable? Or is this accounted for somewhere else in the function?

Yes, the bug is only triggered, when a variable contins only NA-values and when in addition format is NA. If format is NA and there are some values in the data, format will be derived from the data (one of the core-tasks of changeFormat()).


> 
> Some further minor comments:
> 
>     * Could a news entry be added for this change?

sure, I will add one

> 
>     * Would `anyUnknownFormat` be more fitting than `unknownFormat`?
ok

> 
>     * Currently, there is a lot of redundant subsetting in checkFormat (e.g., `GADSdat$dat[, hh]`, which can make the code slower than necessary and also hinders readability. Could in such instances intermediate objects help?

This would be a somewhat bigger change in the code. How nessecary, do you think, would this be? I never realized speed problems when using changeFormat, but maybe you did?

**Comment by beckerbenj** [comment]
Thanks for the change and adding the news entry!

> This would be a somewhat bigger change in the code. How nessecary, do you think, would this be? I never realized speed problems when using changeFormat, but maybe you did?

Indeed, performance is not a big issue but sometimes slightly annoying for bigger data sets (~50,000 rows and ~150 columns can take around 20 seconds; data sets with character variables will take longer, I think). Especially as `checkFormat()` is run per default within `write_spss2()`. Not a deal breaker but faster is always nicer 😃  

Furthermore, I think tackling such changes could both increase performance as well as code readability. Regardless, I would be open to opening a separate issue for this topic if you think such changes would exceed the scope of the current PR. 

``` r
library(eatGADS)

pisa_large <- pisa
pisa_list <- lapply(1:100, FUN = function(x){
  pisa$dat 
})
pisa_large$dat <- do.call(rbind, pisa_list)

dim(pisa_large$dat)
#> [1] 50000   133

microbenchmark::microbenchmark(
  suppressWarnings(suppressMessages(checkFormat(pisa_large))), times = 5
)
#> Unit: seconds
#>                                                         expr      min       lq
#>  suppressWarnings(suppressMessages(checkFormat(pisa_large))) 17.60467 18.86435
#>      mean   median       uq      max neval
#>  19.69898 20.45714 20.62134 20.94739     5
```

<sup>Created on 2024-06-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sachseka** [comment]
> Regardless, I would be open to opening a separate issue for this topic if you think such changes would exceed the scope of the current PR.

Thx! This would be the most convenient for me... further, the current bug(-fix) won't be affected by / is completely independent of this issue.

**Comment by sachseka** [comment]
> Regardless, I would be open to opening a separate issue for this topic if you think such changes would exceed the scope of the current PR.

Thx! This would be the most convenient for me... further, the current bug(-fix) won't be affected by / is completely independent of this issue.

**Pull request merged**
